name: createdhuman
favicon: null
layout_spectrum: 0.25045
typography_spectrum: 0.74593
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1c2d4'
    - '#4d5965'
    - '#6c798a'
    - '#7796b3'
    - '#13161b'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
