name: createdhuman
favicon: null
layout_spectrum: 0.4237651927396655
typography_spectrum: 0.5145241655409336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7518668184056878
  lightness: 0.20570118515752256
  saturation: 0.7700894598383456
  rhythmicContrast: 0.6091992266010493
purpose: []
