name: createdhuman
favicon: null
layout_spectrum: 0.49819
typography_spectrum: 0.5145241655409336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#70191f'
    - '#2c6331'
    - '#7e8aa2'
    - '#313e4f'
    - '#555150'
  brandStrength: 0.7518668184056878
  lightness: 0.20570118515752256
  saturation: 0.7700894598383456
  rhythmicContrast: 0.6091992266010493
purpose: []
