name: createdhuman
favicon: null
layout_spectrum: 0.49458
typography_spectrum: 0.74593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f70bd'
    - '#5e99dd'
    - '#27262c'
    - '#93c7f6'
    - '#eff0f5'
  brandStrength: 0.7518668184056878
  lightness: 0.20570118515752256
  saturation: 0.7700894598383456
  rhythmicContrast: 0.6091992266010493
purpose: []
