name: createdhuman
favicon: null
layout_spectrum: 0.49458
typography_spectrum: 0.74593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9d9895'
    - '#dde3ef'
    - '#5c88c7'
    - '#233d62'
    - '#090c13'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
